version: '3'

services:
  pk-box-manager:
    build: . # Verwendet das Dockerfile im aktuellen Verzeichnis
    restart: always
    ports:
      - '3000:3000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s # Wichtig: Gibt dem Server Zeit zum Starten
